
planner: "Agent"

test_name: "Eval_StdRewardFast"
racing_mode: "Fast"
n_scans: 2
train_mode: "Std"
test_mode: "Std"

n: 5
set_n: 1

random_seed: 10000

n_train_steps: 100000
# n_test_laps: 20
n_test_laps: 50

# max_speed: 8
max_speed: 5

runs:
  - map_name: "f1_aut"
    reward: "Std"







