
# Run with PP and rando

# planner: "PP"
# raceline: True
# test_name: "KernelValidationPP"
# filter: False

planner: "Rando"
test_name: "KernelValidationRandom"
filter: False


# planner: "Rando"
# test_name: "FilterValidationRandom"
# filter: True
## comment out the fast runs.

set_n: 1
n: 1

train_mode: "Std"

test_mode: "Super"
n_test_laps: 50
# n_test_laps: 2

noise_std: 0


n_scans: 1
random_seed: 1000
speed_cap: 8

runs:
  # - map_name: "f1_esp"
  #   racing_mode: "Slow"
  # - map_name: "f1_aut_wide"
  #   racing_mode: "Slow"
  # - map_name: "f1_mco"
  #   racing_mode: "Slow"

  # - map_name: "f1_esp"
  #   racing_mode: "Fast"
  # - map_name: "f1_aut_wide"
  #   racing_mode: "Fast"
  - map_name: "f1_mco"
    racing_mode: "Fast"


