
# Run with PP and rando

planner: "PP"
raceline: False
test_name: "KernelValidationPP"
filter: False
n_test_laps: 2

set_n: 1
n: 1

train_mode: "Std"
test_mode: "Super"


noise_std: 0
n_scans: 1
random_seed: 1000

map_name: "f1_mco"
racing_mode: "Fast"


runs:
  - speed_cap: 4
    test_mode: "Super"
  - speed_cap: 6
    test_mode: "Super"
  - speed_cap: 8
    test_mode: "Super"

  - speed_cap: 4
    test_mode: "Std"
  - speed_cap: 6
    test_mode: "Std"
  - speed_cap: 8
    test_mode: "Std"


