

test_name: "OnlineCompare" # name params
set_n: 1
n: 5

# Testing params
test_mode: "Std"
n_test_laps: 20

noise_std: 0

filter: False

n_scans: 2
random_seed: 10000

map_name: "f1_esp"

runs:
  # - architecture: "PP"
  #   pp_speed_mode: "constant"
  #   raceline: True
  #   n_train_steps: 0
  #   max_speed: 2
  #   reward: "Zero"
  #   train_mode: "Online"

  - architecture: "slow"
    train_mode: "Online"
    n_train_steps: 6000
    reward: "Zero"
    max_speed: 2

  - architecture: "slow"
    train_mode: "Std"
    n_train_steps: 30000
    reward: "Cth"
    max_speed: 2
    


  - architecture: "fast"
    train_mode: "Online"
    n_train_steps: 10000
    reward: "Velocity"
    max_speed: 5

  - architecture: "fast"
    train_mode: "Std"
    n_train_steps: 100000
    reward: "Cth"
    max_speed: 5
    
  # - architecture: "PP"
  #   pp_speed_mode: "raceline"
  #   raceline: True
  #   n_train_steps: 0
  #   max_speed: 5
  #   reward: "Zero"
    


