
planner: "Agent"

test_name: "Online_RewardsSlow" # name params
set_n: 1
n: 5

# agent training parameters
train_mode: "Online"
n_train_steps: 6000

test_mode: "Std"
n_test_laps: 20

noise_std: 0
speed_cap: 5
vehicle_speed: 2

racing_mode: "Slow"
filter: False

n_scans: 2
random_seed: 10000

map_name: "f1_esp"

runs:
  - reward: "Cth"
  - reward: "None"
  - reward: "Progress"
  - reward: "Velocity"



