
planner: "Agent"

test_name: "Online_MaxSpeedsFast" # name params
set_n: 1
n: 5

train_mode: "Online"
n_train_steps: 10000

reward: "Velocity"

n_test_laps: 20

noise_std: 0

racing_mode: "Fast"
filter: False

n_scans: 2
random_seed: 10000

map_name: "f1_esp"

runs:

  - max_speed: 4
    set_n: 4
  - max_speed: 5
    set_n: 5
  - max_speed: 6
    set_n: 6
  - max_speed: 7
    set_n: 7
  - max_speed: 8
    set_n: 8

