

test_name: "OnlineCompare" # name params
set_n: 1
n: 1

# Testing params
test_mode: "Std"
# test_mode: "Super"
# n_test_laps: 50
n_test_laps: 20
# n_test_laps: 2

noise_std: 0
speed_cap: 5
vehicle_speed: 2

racing_mode: "Slow"
# racing_mode: "Fast"
filter: False

n_scans: 2
random_seed: 10000

map_name: "f1_esp"

runs:
  - planner: "Agent"
    racing_mode: "Slow"
    train_mode: "Online"
    n_train_steps: 6000
    reward: "None"
    speed_cap: 2

  - planner: "Agent"
    racing_mode: "Slow"
    train_mode: "Std"
    n_train_steps: 6000
    reward: "Cth"
    speed_cap: 2
    
  - planner: "PP"
    racing_mode: "Slow"
    raceline: True
    speed_cap: 2


  - planner: "Agent"
    racing_mode: "Fast"
    train_mode: "Online"
    n_train_steps: 10000
    reward: "Velocity"
    speed_cap: 8

  - planner: "Agent"
    racing_mode: "Fast"
    train_mode: "Std"
    n_train_steps: 100000
    reward: "Cth"
    speed_cap: 8
    
  - planner: "PP"
    racing_mode: "Fast"
    raceline: True
    speed_cap: 8
    


