
planner: "Agent"

test_name: "Online_RewardsFast" # name params
set_n: 1
n: 1

# agent training parameters
train_mode: "Online"
n_train_steps: 10000


# Testing params
test_mode: "Std"
n_test_laps: 20

noise_std: 0
max_speed: 5
vehicle_speed: 2

# racing_mode: "Slow"
racing_mode: "Fast"
filter: False

n_scans: 2
random_seed: 10000

map_name: "f1_esp"

runs:
  - reward: "Ppps"
  - reward: "Cth"
  - reward: "None"
  - reward: "Progress"
  - reward: "Velocity"
