
planner: "Agent"

test_name: "Racing_vLineRewards"

racing_mode: "Fast"
n_scans: 2
train_mode: "Std"
test_mode: "Std"

n: 5
set_n: 1

random_seed: 10000

n_train_steps: 100000
# n_test_laps: 20
n_test_laps: 50

speed_cap: 8
# speed_cap: 5

map_name: "f1_esp"

runs:
  - reward: "v1"
  - reward: "v2"
  - reward: "v3"
  - reward: "PPPS"






