
planner: "Agent"

test_name: "Racing_PathsSlow"

racing_mode: "Slow"
vehicle_speed: 2
n_scans: 2
train_mode: "Std"
test_mode: "Std"

n: 10
set_n: 1

random_seed: 10000
max_v: 2

n_train_steps: 30000
# n_test_laps: 20
n_test_laps: 50

runs:
  - map_name: "f1_mco"
    reward: "Cth"

  - map_name: "f1_mco"
    reward: "CthRace"






