
test_name: "SlowOnlineVsBaseline" # name params
architecture: "slow"

set_n: 1
n: 3

# agent training parameters
# train_mode: "Online"
test_mode: "Std"

# n_train_steps: 6000
n_test_laps: 20

noise_std: 0
max_speed: 2

filter: False

n_scans: 1
random_seed: 10000
# reward: "Zero"

runs:
  # - map_name: "f1_gbr"
  #   train_mode: "Online"
  #   n_train_steps: 6000
  #   reward: "Zero"
  # - map_name: "f1_esp"
  #   train_mode: "Online"
  #   n_train_steps: 6000
  #   reward: "Zero"
  # - map_name: "f1_aut"
  #   train_mode: "Online"
  #   n_train_steps: 6000
  #   reward: "Zero"
  # - map_name: "f1_mco"
  #   train_mode: "Online"
  #   n_train_steps: 6000
  #   reward: "Zero"

  - map_name: "f1_gbr"
    train_mode: "Std"
    n_train_steps: 30000
    reward: "Progress"
  - map_name: "f1_esp"
    train_mode: "Std"
    n_train_steps: 30000
    reward: "Progress"
  - map_name: "f1_aut"
    train_mode: "Std"
    n_train_steps: 30000
    reward: "Progress"
  - map_name: "f1_mco"
    train_mode: "Std"
    n_train_steps: 30000
    reward: "Progress"

  # - map_name: "f1_gbr"
  #   architecture: "slow"
  # - map_name: "f1_esp"
  #   architecture: "slow"
  # - map_name: "f1_aut"
  #   architecture: "slow"
  # - map_name: "f1_mco"
  #   architecture: "slow"
